const D=[
['Inventário do Meu Mundo','Escolhe três coisas. Dá-lhes um gesto.'],['Catástrofe Produtiva','Faz. Rasga. Continua.'],['O Ponto de Kusama','Um ponto. Outro. Até o campo mudar.'],['O Corpo que Percebe','Fecha os olhos. O corpo começa.'],['Escutar o Silêncio','Escuta o que quase não existe.'],['O Rizoma Interior','Liga sem ordenar.'],['O Cubo Interior','Roda o que ficou.']];
const deck=document.querySelector('#dinamicas');D.forEach((d,i)=>deck.insertAdjacentHTML('beforeend',`<article class="card" data-n="${i+1}"><span class="tag">jogo ${i+1}</span><h2>${d[0]}</h2><p>${d[1]}</p><button class="open" data-engine="${i}">brincar</button></article>`));
const BOOK_FACES=[
  {name:'a porta',prompt:'onde entras',layers:['fundo do túnel','o primeiro vestígio que chama','uma entrada escolhida pelo corpo']},
  {name:'a jaula',prompt:'o que pensavas que era o caminho',layers:['o aviso que não avisa','a regra herdada','a possibilidade de a deslocar']},
  {name:'o chão',prompt:'onde o joelho esfola',layers:['a experiência concreta','o erro que deixou marca','o apoio que ainda existe']},
  {name:'o céu',prompt:'de onde se vê tudo',layers:['teoria da mente em brincadeira','uma distância fértil','o mundo visto por outra face']},
  {name:'o espelho',prompt:'onde te encontras',layers:['mimetismo performático','o gesto que imita e transforma','aquilo que só tu reconheces']},
  {name:'o buraco',prompt:'que não tem fundo e por isso é livre',layers:['a neurofractura','a ausência de protocolo','o próximo possível']}
];
const bookState={face:0,opened:new Set(),note:''};
const faceNav=document.querySelector('.face-nav'),facePanel=document.querySelector('#face-panel');
BOOK_FACES.forEach((f,i)=>faceNav.insertAdjacentHTML('beforeend',`<button type="button" role="tab" id="face-tab-${i}" aria-controls="face-panel" aria-selected="${i===0}" tabindex="${i===0?0:-1}" data-face="${i}"><span>face ${i+1}</span>${f.name}</button>`));
function renderFace(i){bookState.face=i;bookState.opened.add(i);faceNav.querySelectorAll('[data-face]').forEach((b,n)=>{b.setAttribute('aria-selected',n===i);b.tabIndex=n===i?0:-1});const f=BOOK_FACES[i];facePanel.setAttribute('aria-labelledby',`face-tab-${i}`);facePanel.innerHTML=`<div class="face-number" aria-hidden="true">0${i+1}</div><div><span class="tag">face ${i+1} · ${f.prompt}</span><h3>${f.name}</h3><div class="accordion">${f.layers.map((l,n)=>`<details${n===0?' open':''}><summary>camada ${n+1}</summary><p>${l}</p></details>`).join('')}</div><p class="book-progress">${bookState.opened.size} de 6 faces atravessadas · não há ordem correcta</p></div>`}
faceNav.addEventListener('click',e=>{const b=e.target.closest('[data-face]');if(b)renderFace(+b.dataset.face)});
faceNav.addEventListener('keydown',e=>{if(!['ArrowLeft','ArrowRight','Home','End'].includes(e.key))return;e.preventDefault();let i=bookState.face;if(e.key==='ArrowLeft')i=(i+5)%6;if(e.key==='ArrowRight')i=(i+1)%6;if(e.key==='Home')i=0;if(e.key==='End')i=5;renderFace(i);faceNav.querySelector(`[data-face="${i}"]`).focus()});
renderFace(0);
const bookNote=document.querySelector('#book-note'),registerStatus=document.querySelector('#register-status');
document.querySelector('#save-note').onclick=()=>{bookState.note=bookNote.value.trim();registerStatus.textContent=bookState.note?'ficou aqui':'ainda vazio'};
const dlg=document.querySelector('#engine'),body=document.querySelector('#engineBody');dlg.querySelector('.close').onclick=()=>{stopMedia();dlg.close()};dlg.onclick=e=>{if(e.target===dlg){stopMedia();dlg.close()}};dlg.addEventListener('close',()=>stopMedia());
let audio,stream,raf,cosRaf;const state={inventory:[],catastrophe:'',points:0,body:'',silence:'',rizoma:[]};
function stopMedia(){if(stream)stream.getTracks().forEach(t=>t.stop());stream=null;if(raf)cancelAnimationFrame(raf);raf=0;if(audio){const ctx=audio;audio=null;if(ctx.state!=='closed')ctx.close().catch(()=>{})}}
function wrap(i,content){return `<section class="engine"><span class="tag">jogo ${i+1} · fica aqui</span><h2>${D[i][0]}</h2><p class="invitation">${D[i][1]}</p>${content}</section>`}
function canvas(id){return `<canvas class="work" id="${id}" width="900" height="500"></canvas>`}
function pen(c,color='#f2d18b'){const x=c.getContext('2d');x.lineCap='round';x.lineWidth=4;x.strokeStyle=color;let on=false;const p=e=>{const r=c.getBoundingClientRect();return[(e.clientX-r.left)*c.width/r.width,(e.clientY-r.top)*c.height/r.height]};c.onpointerdown=e=>{on=true;c.setPointerCapture(e.pointerId);x.beginPath();x.moveTo(...p(e))};c.onpointermove=e=>{if(on){x.lineTo(...p(e));x.stroke()}};c.onpointerup=()=>on=false;return x}
function tone(freq=110,dur=1){audio??=new AudioContext();const o=audio.createOscillator(),g=audio.createGain();o.frequency.value=freq;g.gain.setValueAtTime(.05,audio.currentTime);g.gain.exponentialRampToValueAtTime(.0001,audio.currentTime+dur);o.connect(g).connect(audio.destination);o.start();o.stop(audio.currentTime+dur)}
function d1(){body.innerHTML=wrap(0,`<div class="engine-grid">${[1,2,3].map(n=>`<div class="panel"><label>Objecto ${n}<input id="o${n}" maxlength="60"></label><label>Carga simbólica<textarea id="c${n}" maxlength="500"></textarea></label><label>Gesto <input id="g${n}" maxlength="8" placeholder="símbolo"></label></div>`).join('')}</div><div class="toolbar"><button class="action" id="manto">gerar manto digital</button></div><div class="result" id="out"></div>`);body.querySelector('#manto').onclick=()=>{state.inventory=[1,2,3].map(n=>({o:body.querySelector('#o'+n).value.trim(),c:body.querySelector('#c'+n).value.trim(),g:body.querySelector('#g'+n).value.trim()}));body.querySelector('#out').textContent=state.inventory.map((v,i)=>`${v.g||'✦'} ${v.o||'objecto '+(i+1)} — ${v.c||'por descobrir'}`).join('\n        ╲  constelação  ╱\n')}}
function d3(){body.innerHTML=wrap(2,`${canvas('kusama')}<div class="toolbar"><button class="action" id="pulse">gesto sonoro</button><button class="action" id="clear">novo campo</button></div><div class="result" id="out">toque ou arraste no campo</div>`);const c=body.querySelector('#kusama'),x=c.getContext('2d');function p(e){const r=c.getBoundingClientRect();return[(e.clientX-r.left)*c.width/r.width,(e.clientY-r.top)*c.height/r.height]}c.onpointerdown=e=>{const[a,b]=p(e);x.beginPath();x.fillStyle=`hsl(${state.points*17%360} 85% 67%)`;x.arc(a,b,4+(state.points%8),0,Math.PI*2);x.fill();state.points++;body.querySelector('#out').textContent=`${state.points} gestos mínimos neste campo`};c.onpointermove=e=>{if(e.buttons)c.onpointerdown(e)};body.querySelector('#pulse').onclick=()=>{tone(60+state.points%80,.4);state.points++};body.querySelector('#clear').onclick=()=>{x.clearRect(0,0,c.width,c.height);state.points=0}}
function d4(){const moves=['perto','longe','lento','rápido','parado'];body.innerHTML=wrap(3,`<div class="layers">${moves.map((l,i)=>`<button data-layer="${i}">${i+1}. ${l}</button>`).join('')}</div><label>uma palavra<textarea id="note" maxlength="200"></textarea></label><div class="result" id="out">escolhe um movimento</div>`);body.querySelectorAll('[data-layer]').forEach(b=>b.onclick=()=>{const i=+b.dataset.layer;tone([40,64,220,96,330][i],[2,1.5,1,2,3][i]);body.querySelector('#out').textContent=moves[i]});body.querySelector('#note').oninput=e=>state.body=e.target.value}
function d5(){body.innerHTML=wrap(4,`${canvas('spec')}<label><input type="checkbox" id="allow-sound"> deixo o som entrar agora</label><div class="toolbar"><button class="action" id="listen" disabled>abrir o ouvido</button><button class="action" id="stop">fechar</button></div><p class="result" id="out">à espera</p>`);const c=body.querySelector('#spec'),x=c.getContext('2d'),allow=body.querySelector('#allow-sound'),listen=body.querySelector('#listen');allow.onchange=()=>listen.disabled=!allow.checked;listen.onclick=async()=>{if(!allow.checked)return;try{audio??=new AudioContext();stream=await navigator.mediaDevices.getUserMedia({audio:true});const a=audio.createAnalyser();a.fftSize=256;audio.createMediaStreamSource(stream).connect(a);const data=new Uint8Array(a.frequencyBinCount);const draw=()=>{a.getByteFrequencyData(data);x.fillStyle='#05070bd0';x.fillRect(0,0,c.width,c.height);const w=c.width/data.length;data.forEach((v,i)=>{x.fillStyle=`hsl(${205+v/8} 80% ${20+v/5}%)`;x.fillRect(i*w,c.height-v*1.7,w-1,v*1.7)});raf=requestAnimationFrame(draw)};draw();body.querySelector('#out').textContent='o silêncio desenha'}catch{body.querySelector('#out').textContent='brinca em silêncio'}};body.querySelector('#stop').onclick=()=>{stopMedia();allow.checked=false;listen.disabled=true;body.querySelector('#out').textContent='ficou silêncio'}}
function d6(){body.innerHTML=wrap(5,`<label>Novo fragmento <input id="frag" maxlength="40"><button class="action" id="add">acrescentar sem apagar</button></label><div class="rizoma" id="rizoma" aria-label="Campo rizomático transformável"></div><div class="result" id="out">arraste os fragmentos para transformar a relação</div>`);const z=body.querySelector('#rizoma');function add(t){const n=document.createElement('button');n.className='node';n.textContent=t;n.style.left=10+Math.random()*75+'%';n.style.top=8+Math.random()*75+'%';z.append(n);let dx,dy;n.onpointerdown=e=>{const r=n.getBoundingClientRect();dx=e.clientX-r.left;dy=e.clientY-r.top;n.setPointerCapture(e.pointerId)};n.onpointermove=e=>{if(!e.buttons)return;const r=z.getBoundingClientRect();n.style.left=Math.max(0,Math.min(r.width-n.offsetWidth,e.clientX-r.left-dx))+'px';n.style.top=Math.max(0,Math.min(r.height-n.offsetHeight,e.clientY-r.top-dy))+'px'};state.rizoma.push(t)}['encontro','território','memória'].forEach(add);body.querySelector('#add').onclick=()=>{const t=body.querySelector('#frag').value.trim();if(t){add(t);body.querySelector('#frag').value=''}}}
function d2play(){body.innerHTML=wrap(1,`${canvas('cat')}<div class="toolbar"><button class="action" data-cat="rasgar">rasgar</button><button class="action" data-cat="cobrir">cobrir</button><button class="action" data-cat="inverter">virar</button><button class="action" data-cat="apagar">sumir</button><button class="action" id="clean">outra vez</button></div><label>o que escapou?<textarea id="survive"></textarea></label><div class="result" id="out">faz primeiro</div>`);const c=body.querySelector('#cat'),x=pen(c);x.fillStyle='#fff';x.font='600 26px Montserrat';x.fillText('começa aqui',35,55);body.querySelectorAll('[data-cat]').forEach(b=>b.onclick=()=>{const k=b.dataset.cat;state.catastrophe=k;if(k==='inverter')c.style.filter='invert(1)';if(k==='cobrir'){x.fillStyle='#111d';x.fillRect(0,0,c.width*.68,c.height)}if(k==='apagar')for(let i=0;i<60;i++)x.clearRect(Math.random()*c.width,Math.random()*c.height,40+Math.random()*120,30+Math.random()*90);if(k==='rasgar'){for(let i=0;i<10;i++){x.strokeStyle='#050505';x.lineWidth=8;x.beginPath();x.moveTo(Math.random()*c.width,0);x.lineTo(Math.random()*c.width,c.height);x.stroke()}}body.querySelector('#out').textContent=`${k}. agora continua.`});body.querySelector('#clean').onclick=()=>{c.style.filter='';x.clearRect(0,0,c.width,c.height)}}
function d7play(){const faces=['corpo','inventário','ruptura','rizoma','ponto','silêncio'];body.innerHTML=wrap(6,`<div class="cube-scene"><div class="cube">${faces.map((f,i)=>`<div class="face f${i+1}">${f}<br><small>${['move','escolhe','vira','liga','repete','escuta'][i]}</small></div>`).join('')}</div></div><div class="toolbar"><button class="action" id="link">rodar comigo</button></div><div class="result" id="out">o cubo espera</div>`);const link=body.querySelector('#link'),cube=body.querySelector('.cube');link.onclick=()=>{cube.classList.toggle('chosen');body.querySelector('#out').textContent=cube.classList.contains('chosen')?'agora roda contigo':'o cubo espera'}}
const engines=[d1,d2play,d3,d4,d5,d6,d7play];deck.onclick=e=>{const b=e.target.closest('[data-engine]');if(!b)return;engines[+b.dataset.engine]();dlg.showModal()};
const cos=document.querySelector('#cosmos'),cx=cos.getContext('2d');let move=true,stars=[];function size(){cos.width=innerWidth*devicePixelRatio;cos.height=innerHeight*devicePixelRatio;stars=Array.from({length:Math.min(150,innerWidth/7)},()=>({x:Math.random()*cos.width,y:Math.random()*cos.height,r:Math.random()*2+.4,v:Math.random()*.18+.03}))}function drawCosmosFrame(){cx.clearRect(0,0,cos.width,cos.height);cx.fillStyle='#bce3ff';stars.forEach(s=>{if(move){s.y+=s.v;if(s.y>cos.height)s.y=0}cx.globalAlpha=.2+s.r/3;cx.beginPath();cx.arc(s.x,s.y,s.r,0,7);cx.fill()})}function cosmosTick(){cosRaf=0;if(document.hidden||!move)return;drawCosmosFrame();cosRaf=requestAnimationFrame(cosmosTick)}function scheduleCosmos(){if(cosRaf!==0)return;if(document.hidden||!move)return;cosRaf=requestAnimationFrame(cosmosTick)}function stopCosmos(){if(cosRaf!==0)cancelAnimationFrame(cosRaf);cosRaf=0}addEventListener('resize',size);addEventListener('visibilitychange',()=>{if(document.hidden)stopCosmos();else{drawCosmosFrame();if(move)scheduleCosmos()}});size();scheduleCosmos();document.querySelector('#motion').onclick=e=>{move=!move;e.currentTarget.setAttribute('aria-pressed',move);e.currentTarget.textContent=move?'o céu mexe':'o céu parou';if(move)scheduleCosmos();else stopCosmos()};
