const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches,opening=document.querySelector('#opening'),territory=document.querySelector('#territory');
document.querySelector('#enterAtlas').onclick=()=>{opening.classList.add('leaving');setTimeout(()=>{opening.hidden=true;territory.hidden=false;document.querySelector('.author-portal')?.focus()},reduced?10:520)};
const closeBackdrop=d=>d.addEventListener('click',e=>{if(e.target===d)d.close()});
const ticket=document.querySelector('#ticket'),ticketResponse=document.querySelector('#ticket-response');let catalogue=[];
fetch('catalogo-curatorial.json',{cache:'no-store'}).then(r=>r.ok?r.json():Promise.reject()).then(d=>catalogue=Array.isArray(d.entradas)?d.entradas:[]).catch(()=>catalogue=[]);
document.querySelectorAll('[data-ticket]').forEach(p=>p.onclick=()=>{ticketResponse.textContent='';ticket.showModal()});document.querySelector('.ticket-close').onclick=()=>ticket.close();closeBackdrop(ticket);
const pick=f=>{const c=catalogue.filter(f);return c.length?c[Math.floor(Math.random()*c.length)]:null};
document.querySelectorAll('[data-ticket-action]').forEach(b=>b.onclick=()=>{const k=b.dataset.ticketAction,item=k==='brincar'?pick(e=>e.familia==='jogo'):k==='convite'?pick(e=>e.id==='festas-827'||e.mecanica==='convidar'):pick(()=>true);ticketResponse.textContent=item?item.nome+' · '+item.convite:'o território ainda está a chegar'});
function focusCuradoria(id,family){const locate=n=>{const card=document.querySelector('[data-curadoria="'+CSS.escape(id)+'"]');if(!card&&n>0)return setTimeout(()=>locate(n-1),120);if(!card)return;document.querySelector('[data-family="'+CSS.escape(family)+'"]')?.click();card.scrollIntoView({behavior:reduced?'auto':'smooth',block:'center'});setTimeout(()=>card.querySelector('[data-curadoria]')?.click(),reduced?20:500)};locate(20)}
document.querySelectorAll('[data-focus-id]').forEach(p=>p.onclick=()=>focusCuradoria(p.dataset.focusId,p.dataset.focusFamily));
const contribution=document.querySelector('#contribution'),nuno=document.querySelector('[data-contribute]'),trace=document.querySelector('#trace-text'),consent=document.querySelector('#trace-local'),save=document.querySelector('#trace-save'),status=document.querySelector('#trace-status'),key='atlas-milk-vestigio-local-v1';
nuno.onclick=()=>{nuno.dataset.active='true';trace.value=localStorage.getItem(key)||'';consent.checked=false;save.disabled=true;status.textContent=trace.value?'rascunho local recuperado':'nenhum envio externo';contribution.showModal();trace.focus()};
consent.onchange=()=>save.disabled=!consent.checked;save.onclick=()=>{if(!consent.checked)return;const v=trace.value.trim();v?localStorage.setItem(key,v):localStorage.removeItem(key);status.textContent=v?'ficou neste aparelho':'nenhum vestígio guardado'};document.querySelector('#trace-remove').onclick=()=>{localStorage.removeItem(key);trace.value='';status.textContent='retirado deste aparelho'};document.querySelector('.contribution-close').onclick=()=>contribution.close();contribution.addEventListener('close',()=>nuno.dataset.active='false');closeBackdrop(contribution);