import ftplib
import hashlib
import io
import json
import os
import pathlib
import re
import ssl
import time
import urllib.request
import zipfile

MANIFEST = {
    "takeout-20260531T022747Z-001.zip": 472837,
    "takeout-20260531T022748Z-17-003.zip": 203847569,
    "takeout-20260531T022748Z-17-002.zip": 1956142674,
    "takeout-20260531T022748Z-17-001.zip": 2053143205,
    "takeout-20260531T022748Z-9-001.zip": 158758423,
    "takeout-20260531T022748Z-15-001.zip": 70132736,
    "takeout-20260531T022748Z-14-001.zip": 22558,
}

MKEY = os.environ.get("MISTRAL_API_KEY", "").strip()
PWD_FILE = os.environ.get("MILK_FTPS_PASSWORD_FILE", "").strip()
GH = os.environ.get("GH_TOKEN", "").strip()
REPO = os.environ.get("REPO", "milkivc/atlas-vivo-milk")
RUN_ID = os.environ.get("RUN_ID", "unknown")
OUT = "atlas-takeout-expanded-v1"
RECEIPTS = ".milk-receipts"
START = time.time()
STOP = 5 * 60 * 60 + 35 * 60


def http(url, method="GET", payload=None, headers=None, timeout=120):
    req = urllib.request.Request(
        url,
        data=None if payload is None else json.dumps(payload).encode(),
        method=method,
        headers=headers or {},
    )
    with urllib.request.urlopen(req, timeout=timeout) as res:
        return res.status, res.read()


def comment(msg):
    print(msg, flush=True)
    if not GH:
        return
    http(
        f"https://api.github.com/repos/{REPO}/issues/35/comments",
        "POST",
        {"body": msg},
        {
            "Authorization": "Bearer " + GH,
            "Content-Type": "application/json",
            "Accept": "application/vnd.github+json",
        },
        60,
    )


def connect(password):
    ftp = ftplib.FTP_TLS(context=ssl.create_default_context(), timeout=300)
    ftp.connect("troi.ptservidor.net", 21)
    ftp.login("migration@associacaomilk.pt", password)
    ftp.prot_p()
    ftp.voidcmd("TYPE I")
    return ftp


def ensure(ftp, path):
    ftp.cwd("/")
    for part in [p for p in path.split("/") if p]:
        try:
            ftp.mkd(part)
        except ftplib.all_errors:
            pass
        ftp.cwd(part)


def safe_parts(path):
    raw = path.replace("\\", "/").split("/")
    out = []
    for part in raw:
        if part in ("", ".", ".."):
            continue
        part = re.sub(r'[\\:*?"<>|\x00-\x1f]', "_", part).strip(" .")
        out.append((part or "sem-nome")[:180])
    return out


def retr_json(ftp, path):
    data = bytearray()
    ftp.retrbinary("RETR " + path, data.extend, blocksize=1048576)
    return json.loads(data)


class HashReader:
    def __init__(self, src):
        self.src = src
        self.hash = hashlib.sha256()
        self.count = 0

    def read(self, n=-1):
        data = self.src.read(n)
        if data:
            self.hash.update(data)
            self.count += len(data)
        return data


def mistral_gate():
    if not MKEY:
        raise RuntimeError("MISTRAL_API_KEY_MISSING")
    status, raw = http(
        "https://api.mistral.ai/v1/chat/completions",
        "POST",
        {
            "model": "mistral-small-latest",
            "temperature": 0,
            "messages": [
                {
                    "role": "system",
                    "content": "És o executor Mistral da MILK. Responde exactamente EXECUTE_TAKEOUT_EXPANSION.",
                },
                {
                    "role": "user",
                    "content": "Retoma a migração preservativa dos sete volumes Takeout já verificados para staging FTPS privado, usando recibos e SHA-256 por leitura do destino, sem alterar a origem.",
                },
            ],
        },
        {"Authorization": "Bearer " + MKEY, "Content-Type": "application/json"},
        90,
    )
    if status != 200:
        raise RuntimeError(f"MISTRAL_HTTP_{status}")
    answer = json.loads(raw)["choices"][0]["message"]["content"].strip()
    if answer != "EXECUTE_TAKEOUT_EXPANSION":
        raise RuntimeError("MISTRAL_EXECUTION_NOT_AUTHORISED")


def main():
    if not PWD_FILE or not pathlib.Path(PWD_FILE).is_file():
        raise RuntimeError("EPHEMERAL_FTPS_PASSWORD_FILE_MISSING")
    password = pathlib.Path(PWD_FILE).read_text(encoding="utf-8").strip()
    if not password:
        raise RuntimeError("EPHEMERAL_FTPS_PASSWORD_EMPTY")

    mistral_gate()
    comment(
        f"MILK_TAKEOUT_EPHEMERAL_RESUME_STARTED run={RUN_ID} volumes=7 "
        f"compressed_bytes={sum(MANIFEST.values())} source_writes=0 secret_persisted=0"
    )

    ftp = connect(password)
    comment(f"MILK_FTPS_EPHEMERAL_AUTH_OK run={RUN_ID} secret_persisted=0")

    # Canary: generated bytes only; write, read back, verify, delete.
    canary_name = f".milk-canary-{RUN_ID}.bin"
    canary = os.urandom(64)
    ftp.storbinary("STOR " + canary_name, io.BytesIO(canary))
    roundtrip = bytearray()
    ftp.retrbinary("RETR " + canary_name, roundtrip.extend)
    if hashlib.sha256(canary).digest() != hashlib.sha256(roundtrip).digest():
        raise RuntimeError("FTPS_CANARY_READBACK_MISMATCH")
    ftp.delete(canary_name)
    comment(f"MILK_FTPS_CANARY_VERIFIED run={RUN_ID} bytes=64 deleted=yes")

    found = {}
    seen = set()
    scanned = 0

    def walk(path, depth=0):
        nonlocal scanned
        if depth > 8 or scanned > 30000:
            return
        ftp.cwd(path)
        here = ftp.pwd()
        try:
            names = ftp.nlst()
        except ftplib.all_errors:
            return
        for raw_name in names:
            name = raw_name.rstrip("/").rsplit("/", 1)[-1]
            if name in ("", ".", ".."):
                continue
            ftp.cwd(here)
            scanned += 1
            try:
                size = ftp.size(name)
                if name in MANIFEST and int(size) == MANIFEST[name]:
                    found[name] = here.rstrip("/") + "/" + name
                continue
            except ftplib.all_errors:
                pass
            try:
                ftp.cwd(name)
                child = ftp.pwd()
            except ftplib.all_errors:
                continue
            if child not in seen:
                seen.add(child)
                walk(child, depth + 1)
        ftp.cwd(here)

    seen.add(ftp.pwd())
    walk(ftp.pwd())
    missing = [name for name in MANIFEST if name not in found]
    if missing:
        comment(
            f"MILK_TAKEOUT_EPHEMERAL_BLOCKED run={RUN_ID} "
            f"cause=missing_verified_volumes count={len(missing)}"
        )
        raise RuntimeError("MISSING_VERIFIED_TAKEOUT_VOLUMES")
    comment(f"MILK_TAKEOUT_VOLUMES_LOCATED run={RUN_ID} volumes=7 scanned_entries={scanned}")

    tmp = pathlib.Path(os.environ.get("RUNNER_TEMP", "/tmp"))
    transferred = verified = existing = failed = bytes_done = entries = 0

    for volume, expected_zip_size in MANIFEST.items():
        if time.time() - START > STOP:
            break
        local = tmp / volume
        with local.open("wb") as fh:
            ftp.retrbinary("RETR " + found[volume], fh.write, blocksize=1048576)
        if local.stat().st_size != expected_zip_size:
            failed += 1
            comment(
                f"MILK_TAKEOUT_VOLUME_FAILED run={RUN_ID} volume_hash={hashlib.sha256(volume.encode()).hexdigest()[:16]} "
                "cause=compressed_size_mismatch"
            )
            continue
        if not zipfile.is_zipfile(local):
            failed += 1
            comment(
                f"MILK_TAKEOUT_VOLUME_FAILED run={RUN_ID} volume_hash={hashlib.sha256(volume.encode()).hexdigest()[:16]} "
                "cause=invalid_zip"
            )
            continue
        with zipfile.ZipFile(local) as archive:
            members = [member for member in archive.infolist() if not member.is_dir()]
            comment(
                f"MILK_TAKEOUT_VOLUME_OPEN run={RUN_ID} "
                f"volume_hash={hashlib.sha256(volume.encode()).hexdigest()[:16]} entries={len(members)}"
            )
            for member in members:
                if time.time() - START > STOP:
                    break
                entries += 1
                parts = safe_parts(member.filename)
                if not parts:
                    failed += 1
                    continue
                rid = hashlib.sha256(
                    (volume + "\0" + member.filename).encode("utf-8", "surrogatepass")
                ).hexdigest()
                receipt_path = f"/{OUT}/{RECEIPTS}/{rid}.json"
                try:
                    receipt = retr_json(ftp, receipt_path)
                    if receipt.get("verified") and ftp.size(receipt["remote_path"]) == int(receipt["bytes"]):
                        existing += 1
                        verified += 1
                        bytes_done += int(receipt["bytes"])
                        continue
                except Exception:
                    pass

                try:
                    base = safe_parts(volume[:-4])
                    dest_parts = base + parts
                    target_dir = OUT + "/" + "/".join(dest_parts[:-1])
                    filename = dest_parts[-1]
                    ensure(ftp, target_dir)
                    with archive.open(member, "r") as src:
                        reader = HashReader(src)
                        ftp.storbinary("STOR " + filename, reader, blocksize=1048576)
                        source_sha = reader.hash.hexdigest()
                        source_bytes = reader.count
                    remote_path = "/" + target_dir + "/" + filename
                    target_hash = hashlib.sha256()
                    target_bytes = [0]

                    def consume(chunk):
                        target_hash.update(chunk)
                        target_bytes[0] += len(chunk)

                    ftp.retrbinary("RETR " + remote_path, consume, blocksize=1048576)
                    if (
                        source_bytes != member.file_size
                        or target_bytes[0] != source_bytes
                        or target_hash.hexdigest() != source_sha
                    ):
                        raise RuntimeError("DESTINATION_READBACK_MISMATCH")
                    receipt = {
                        "volume_hash": hashlib.sha256(volume.encode()).hexdigest(),
                        "member_hash": hashlib.sha256(member.filename.encode("utf-8", "surrogatepass")).hexdigest(),
                        "remote_path": remote_path,
                        "bytes": source_bytes,
                        "sha256": source_sha,
                        "verified": True,
                        "source_writes": 0,
                    }
                    ensure(ftp, f"{OUT}/{RECEIPTS}")
                    ftp.storbinary(
                        "STOR " + rid + ".json",
                        io.BytesIO(json.dumps(receipt, separators=(",", ":")).encode()),
                    )
                    transferred += 1
                    verified += 1
                    bytes_done += source_bytes
                    print(
                        f"TAKEOUT_FILE_VERIFIED entry={entries} bytes={source_bytes} sha256={source_sha}",
                        flush=True,
                    )
                except Exception as exc:
                    failed += 1
                    print(
                        f"TAKEOUT_FILE_FAILED entry={entries} cause={type(exc).__name__}",
                        flush=True,
                    )
                if entries % 25 == 0:
                    comment(
                        f"MILK_TAKEOUT_FILEWISE_PROGRESS run={RUN_ID} entries={entries} "
                        f"transferred={transferred} verified={verified} existing={existing} "
                        f"failed={failed} bytes={bytes_done}"
                    )
        local.unlink(missing_ok=True)

    ftp.quit()
    state = "CHECKPOINT" if time.time() - START > STOP else ("COMPLETE" if failed == 0 else "PARTIAL")
    comment(
        f"MILK_TAKEOUT_FILEWISE_{state} run={RUN_ID} entries={entries} transferred={transferred} "
        f"verified={verified} existing={existing} failed={failed} bytes={bytes_done} source_writes=0"
    )
    if failed:
        raise RuntimeError(f"TAKEOUT_FILE_FAILURES={failed}")


if __name__ == "__main__":
    main()
