name: Sync with ORCID

on:
  release:
    types: [published]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Notify ORCID
        env:
          ORCID_ID: "0009-0004-9132-2925"
        run: |
          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.ORCID_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d '{"work": {"title": "${{ github.event.release.name }}", "doi": "${{ env.DOI }}", "url": "${{ github.event.release.html_url }}", "contributors": [{"orcid": "'$ORCID_ID'", "credit-name": "Eduardo Maurício Vieira Cabral e Araujo"}]}}' \
            https://api.orcid.org/v3.0/$ORCID_ID/work
